# Generated by Django 3.1.1 on 2020-10-02 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(verbose_name='дата приема заказа')),
                ('complete_date', models.DateTimeField(verbose_name='дата завершения заказа')),
                ('weight', models.FloatField(default=0)),
                ('preorder_weight', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('prepayment', models.FloatField(default=0)),
                ('comment', models.CharField(max_length=255)),
                ('status', models.CharField(default='new', max_length=255)),
                ('ads', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('size', models.FloatField(default=0)),
                ('photo', models.CharField(max_length=255)),
                ('orders', models.ManyToManyField(to='main.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='отчество')),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('orders', models.ManyToManyField(to='main.Order')),
            ],
        ),
    ]
