# Generated by Django 3.1.2 on 2020-11-19 16:52

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=255)),
                ('date', models.DateTimeField()),
                ('comment_type', models.CharField(default='comment', max_length=255)),
                ('label', models.CharField(default='', max_length=255)),
                ('prev', models.CharField(default='', max_length=255)),
                ('new', models.CharField(default='', max_length=255)),
                ('place', models.CharField(default='', max_length=255)),
                ('identification', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(verbose_name='дата приема заказа')),
                ('complete_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата завершения заказа')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=65)),
                ('preorder_weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=65)),
                ('price', models.DecimalField(decimal_places=2, max_digits=65)),
                ('prepayment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=65)),
                ('status', models.CharField(default='Создан', max_length=255)),
                ('ads', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата завершения заказа')),
                ('complete_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата завершения заказа')),
                ('preorder_weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=65)),
                ('category', models.CharField(default='', max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('status', models.CharField(default='Создан', max_length=255)),
                ('size', models.FloatField(default=0)),
                ('photo', models.TextField(default='')),
                ('comments', models.ManyToManyField(to='main.Comment')),
                ('orders', models.ManyToManyField(to='main.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('my_count', models.DecimalField(decimal_places=2, max_digits=65)),
                ('client_count', models.DecimalField(decimal_places=2, max_digits=65)),
                ('type_operation', models.CharField(max_length=25)),
                ('orders', models.ManyToManyField(to='main.Order')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='orders',
            field=models.ManyToManyField(to='main.Order'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='отчество')),
                ('phone', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('communication_type', models.CharField(max_length=255)),
                ('orders', models.ManyToManyField(to='main.Order')),
            ],
        ),
    ]
