# Generated by Django 3.1.1 on 2020-10-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201006_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('my_price', models.CharField(max_length=255)),
                ('client_price', models.CharField(max_length=255)),
                ('type_operation', models.CharField(max_length=255)),
            ],
        ),
    ]
