# Generated by Django 3.1.1 on 2020-10-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cash'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cash',
            new_name='Payment',
        ),
    ]
