# Generated by Django 3.1.1 on 2020-10-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_payment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='orders',
            field=models.ManyToManyField(to='main.Order'),
        ),
    ]
