# Generated by Django 3.1.2 on 2020-11-04 13:28

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201021_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='complete_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата завершения заказа'),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=65),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата завершения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='preorder_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=65),
        ),
    ]
