# Generated by Django 3.1.2 on 2020-11-07 21:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201104_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='new', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=65),
        ),
    ]
