# Generated by Django 3.1.2 on 2020-11-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201108_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Создан', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='Создан', max_length=255),
        ),
    ]
