# Generated by Django 3.1.2 on 2020-11-10 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201110_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата завершения заказа'),
        ),
    ]
