# Generated by Django 3.1.2 on 2020-11-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='label',
            field=models.CharField(default='', max_length=255),
        ),
    ]
